import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding test data for Crossref testing...');

  // Removed deleteMany to avoid wiping out existing papers
  await prisma.crossrefDeposit.deleteMany({
    where: { paper: { title: { startsWith: 'Automated Test Paper' } } }
  });
  // 1. Create Publisher Settings
  await prisma.crossrefSettings.upsert({
    where: { id: 'test-publisher' },
    update: {},
    create: {
      id: 'test-publisher',
      publisherName: 'Visenary Analytics Research Association',
      publisherEmail: 'admin@visenary.com',
      doiPrefix: '10.66572',
      crossrefUser: 'test-user',
      crossrefPass: 'test-pass',
      environment: 'sandbox',
      depositorName: 'Automated QA',
      depositorEmail: 'qa@visenary.com',
      autoDeposit: true,
      autoGenerateDoi: true,
    }
  });

  // 2. Create 14 Journals
  const journals = [
    { name: 'IJARCM', short: 'ijarcm' },
    { name: 'WJIIS', short: 'wjiis' },
    { name: 'IJIPAL', short: 'ijipal' },
    { name: 'GJOCAI', short: 'gjocai' },
    { name: 'AJOAMS', short: 'ajoams' },
    { name: 'AJOMAIT', short: 'ajomait' },
    { name: 'EJAAMSS', short: 'ejaamss' },
    { name: 'EJFFABLS', short: 'ejffabls' },
    { name: 'EJLILGP', short: 'ejlilgp' },
    { name: 'EJIMAPSS', short: 'ejimapss' },
    { name: 'EJAUIAPAR', short: 'ejauiapar' },
    { name: 'INSIGHTONIX', short: 'insightonix' },
    { name: 'EJOAS', short: 'ejoas' },
    { name: 'IJLSCL', short: 'ijlscl' }
  ];

  for (const j of journals) {
    const site = await prisma.site.upsert({
      where: { id: j.short },
      update: {},
      create: {
        id: j.short,
        name: j.name,
        domain: `${j.short}.example.com`,
        abbreviation: j.short,
      }
    });

    await prisma.crossrefJournalSettings.upsert({
      where: { siteId: site.id },
      update: {},
      create: {
        siteId: site.id,
        journalName: j.name,
        shortName: j.short,
        issn: `1234-${j.short.toUpperCase().substring(0, 4)}`,
        publisher: 'Visenary Analytics Research Association',
        crossrefPrefix: '10.66572'
      }
    });
  }

  // 3. Create a Test User (Author)
  const author = await prisma.user.upsert({
    where: { email: 'author@test.com' },
    update: {},
    create: {
      email: 'author@test.com',
      firstName: 'John',
      lastName: 'Doe',
      role: 'AUTHOR',
      passwordHash: 'dummy'
    }
  });

  // 4. Generate 100 Test Articles
  const testSiteAbbreviations = journals.map(j => j.short);
  const allSites = await prisma.site.findMany({
    where: { abbreviation: { in: testSiteAbbreviations } }
  });
  console.log(`Found ${allSites.length} test sites. Generating papers...`);

  for (let i = 1; i <= 100; i++) {
    const site = allSites[i % allSites.length];
    
    // Create an Issue to tie to (use i for issueNumber to avoid unique constraint)
    const issue = await prisma.issue.upsert({
      where: { id: `test-issue-${site.id}-${i}` },
      update: {},
      create: {
        id: `test-issue-${site.id}-${i}`,
        title: `Volume 1 Issue ${i}`,
        volume: '1',
        issueNumber: String(i),
        year: 2026,
        siteId: site.id,
        publishDate: new Date('2026-01-01'),
      }
    });

    await prisma.paper.upsert({
      where: { id: `test-paper-${site.id}-${i}` },
      update: {},
      create: {
        id: `test-paper-${site.id}-${i}`,
        title: `Automated Test Paper ${i}`,
        abstract: 'This is an automatically generated abstract for QA testing the Crossref DOI module.',
        status: 'PUBLISHED',
        publishedAt: new Date('2026-01-01'),
        publicationDate: new Date('2026-01-01'),
        volumeNumber: '1',
        issueNumber: String(i),
        uniqueNumber: String(i),
        siteId: site.id,
        submitterId: author.id,
        issueId: issue.id,
        filePath: `/uploads/test/paper-${i}.pdf`,
        paperAuthors: {
          create: [
            {
              userId: author.id,
              authorOrder: 1,
            }
          ]
        },
        paperContent: {
          create: {
            references: [
              'Reference 1: Smith, J. (2025). Automated QA.',
              'Reference 2: Doe, J. (2025). Testing.'
            ].join('\n')
          }
        }
      }
    });
  }

  console.log('Seeding completed. 100 articles generated.');
}

main()
  .catch(e => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
