export const dynamic = 'force-dynamic';
import { NextResponse } from 'next/server';
import { getServerSession } from 'next-auth/next';
import { authOptions } from '@/lib/auth';
import { prisma } from '@/lib/prisma';
import { encrypt, decrypt } from '@/lib/crossref/crypto';

export async function GET(req: Request) {
  try {
    const session = await getServerSession(authOptions);
    if (!session || session.user.role !== 'ADMIN') {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const settings = await prisma.crossrefSettings.findFirst();
    if (settings) {
      // Decrypt password before sending to client, or just send a dummy string to indicate it exists
      return NextResponse.json({
        ...settings,
        crossrefPass: settings.crossrefPass ? '********' : '' // Don't send actual password
      });
    }

    return NextResponse.json(null);
  } catch (error: any) {
    console.error('Crossref settings GET error:', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

export async function POST(req: Request) {
  try {
    const session = await getServerSession(authOptions);
    if (!session || session.user.role !== 'ADMIN') {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const data = await req.json();
    const existing = await prisma.crossrefSettings.findFirst();

    // If a new password is provided, encrypt it. If not (and it's '********'), keep the old one.
    let finalPass = existing?.crossrefPass || '';
    if (data.crossrefPass && data.crossrefPass !== '********') {
      finalPass = encrypt(data.crossrefPass);
    }

    const updateData = {
      publisherName: data.publisherName,
      publisherEmail: data.publisherEmail,
      doiPrefix: data.doiPrefix,
      crossrefUser: data.crossrefUser,
      crossrefPass: finalPass,
      environment: data.environment,
      depositorName: data.depositorName,
      depositorEmail: data.depositorEmail,
      autoDeposit: data.autoDeposit,
      autoGenerateDoi: data.autoGenerateDoi,
      retryFailed: data.retryFailed
    };

    let result;
    if (existing) {
      result = await prisma.crossrefSettings.update({
        where: { id: existing.id },
        data: updateData
      });
    } else {
      result = await prisma.crossrefSettings.create({
        data: updateData
      });
    }

    return NextResponse.json({ success: true, settings: result });
  } catch (error: any) {
    console.error('Crossref settings POST error:', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
