'use client';

import { useState, useEffect } from 'react';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { Loader2 } from 'lucide-react';
import { toast } from 'sonner';

export default function CrossrefSettingsPage() {
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [settings, setSettings] = useState({
    publisherName: '',
    publisherEmail: '',
    doiPrefix: '',
    crossrefUser: '',
    crossrefPass: '',
    environment: 'sandbox',
    depositorName: '',
    depositorEmail: '',
    autoDeposit: false,
    autoGenerateDoi: false,
    retryFailed: false
  });

  useEffect(() => {
    fetch('/api/admin/crossref/settings')
      .then(res => res.json())
      .then(data => {
        if (data && !data.error) {
          setSettings(s => ({ ...s, ...data }));
        }
      })
      .finally(() => setLoading(false));
  }, []);

  const handleChange = (field: string, value: any) => {
    setSettings(s => ({ ...s, [field]: value }));
  };

  const handleSave = async () => {
    setSaving(true);
    try {
      const res = await fetch('/api/admin/crossref/settings', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(settings)
      });
      const data = await res.json();
      if (res.ok) {
        toast.success('Crossref settings saved successfully');
      } else {
        throw new Error(data.error);
      }
    } catch (err: any) {
      toast.error(err.message || 'Failed to save settings');
    } finally {
      setSaving(false);
    }
  };

  if (loading) {
    return <div className="p-8 flex justify-center"><Loader2 className="animate-spin" /></div>;
  }

  return (
    <div className="p-8 max-w-4xl mx-auto space-y-6">
      <h1 className="text-3xl font-bold tracking-tight">Crossref Settings</h1>
      <p className="text-muted-foreground">Configure global DOI generation and Crossref API credentials.</p>

      <Card>
        <CardHeader>
          <CardTitle>API Credentials</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label>Crossref Username</Label>
              <Input 
                value={settings.crossrefUser} 
                onChange={e => handleChange('crossrefUser', e.target.value)} 
              />
            </div>
            <div className="space-y-2">
              <Label>Crossref Password</Label>
              <Input 
                type="password"
                value={settings.crossrefPass} 
                onChange={e => handleChange('crossrefPass', e.target.value)} 
              />
            </div>
            <div className="space-y-2">
              <Label>DOI Prefix</Label>
              <Input 
                value={settings.doiPrefix} 
                placeholder="e.g. 10.66572"
                onChange={e => handleChange('doiPrefix', e.target.value)} 
              />
            </div>
            <div className="space-y-2">
              <Label>Environment</Label>
              <select 
                className="w-full flex h-10 rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background"
                value={settings.environment}
                onChange={e => handleChange('environment', e.target.value)}
              >
                <option value="sandbox">Sandbox (Testing)</option>
                <option value="production">Production</option>
              </select>
            </div>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Publisher & Depositor Details</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label>Publisher Name</Label>
              <Input 
                value={settings.publisherName} 
                onChange={e => handleChange('publisherName', e.target.value)} 
              />
            </div>
            <div className="space-y-2">
              <Label>Publisher Email</Label>
              <Input 
                type="email"
                value={settings.publisherEmail} 
                onChange={e => handleChange('publisherEmail', e.target.value)} 
              />
            </div>
            <div className="space-y-2">
              <Label>Depositor Name</Label>
              <Input 
                value={settings.depositorName} 
                onChange={e => handleChange('depositorName', e.target.value)} 
              />
            </div>
            <div className="space-y-2">
              <Label>Depositor Email</Label>
              <Input 
                type="email"
                value={settings.depositorEmail} 
                onChange={e => handleChange('depositorEmail', e.target.value)} 
              />
            </div>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Automation</CardTitle>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="flex items-center justify-between">
            <div className="space-y-0.5">
              <Label>Auto-generate DOI on Publish</Label>
              <div className="text-sm text-muted-foreground">Automatically assign DOI when paper status changes to PUBLISHED</div>
            </div>
            <Switch 
              checked={settings.autoGenerateDoi} 
              onCheckedChange={v => handleChange('autoGenerateDoi', v)} 
            />
          </div>
          <div className="flex items-center justify-between">
            <div className="space-y-0.5">
              <Label>Auto-deposit to Crossref</Label>
              <div className="text-sm text-muted-foreground">Queue XML for deposit immediately after DOI is generated</div>
            </div>
            <Switch 
              checked={settings.autoDeposit} 
              onCheckedChange={v => handleChange('autoDeposit', v)} 
            />
          </div>
          <div className="flex items-center justify-between">
            <div className="space-y-0.5">
              <Label>Auto-retry Failed Deposits</Label>
              <div className="text-sm text-muted-foreground">Background worker will retry up to 3 times</div>
            </div>
            <Switch 
              checked={settings.retryFailed} 
              onCheckedChange={v => handleChange('retryFailed', v)} 
            />
          </div>
        </CardContent>
      </Card>

      <div className="flex justify-end">
        <Button onClick={handleSave} disabled={saving}>
          {saving && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
          Save Settings
        </Button>
      </div>
    </div>
  );
}
